exp_name: exp_open_es
save_path: outputs/${exp_name}
seed: 42
hooks: []
learning_rate: 0.001
epochs: 100

defaults:
  - trainer: es_trainer
  - dataset: pmlb_mushroom
  - model: linear
  - optimizer: adam
  - loss: cross_entropy