exp_name: "SGD_${hydra:runtime.choices.optimizer}_${dataset.name}"
save_path: outputs/${exp_name}
seed: 42
hooks: []
learning_rate: 0.001
epochs: 100
eval_every: 1

defaults:
  - trainer: sgd_trainer
  - dataset: pmlb_mushroom
  - model: linear
  - optimizer: adam
  - loss: cross_entropy
  - _self_


hydra:
  job:
    name: ${exp_name}
  run:
    dir: outputs/${exp_name}